### ISSUE TITLE
network initialization isn't mac compatible

### ISSUE THREAD

**Issue by Kkevsterrr** [ecthros/pina-colada#65]

**Comment by ecthros** [comment]
Lemme know what the error you got was - I recently tried to do this on wifi and I think it might be an issue with scapy

**Comment by Kkevsterrr** [comment]
Initializing Network DB...
Password:
Traceback (most recent call last):
  File "server.py", line 255, in <module>
    servers["PinaColada"] = PinaColadaServer("PinaColada", 9999)
  File "server.py", line 46, in __init__
    self.core = core.PinaColada()
  File "/Volumes/KCB_Storage/Users/koolkevin/Code/Projects/pina-colada/core.py", line 26, in __init__
    self.network = init_network()
  File "/Volumes/KCB_Storage/Users/koolkevin/Code/Projects/pina-colada/network.py", line 80, in init_network
    thisComp = Network()
  File "/Volumes/KCB_Storage/Users/koolkevin/Code/Projects/pina-colada/network.py", line 53, in __init__
    self.findSubnet()
  File "/Volumes/KCB_Storage/Users/koolkevin/Code/Projects/pina-colada/network.py", line 36, in findSubnet
    self.subnet = re.search("(\d*\.\d*\.\d*\.)", self.ip).group(0) + "0/24"
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by ecthros** [comment]
that looks to me like it can't find the ip of your box, which is actually a problem... ill look at it later if we can

**Comment by Kkevsterrr** [comment]
The grepping for an ip address from ifconfig is highly platform dependent is the issue - see https://stackoverflow.com/questions/24196932/how-can-i-get-the-ip-address-of-eth0-in-python. I have no problem just using netifaces, or to keep dependencies lighter, doing it the second way, but we definitely shouldn't rely on grepping through a subprocess call
